# Generated by Django 4.2.2 on 2023-06-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customeraddress_default_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='default_address',
            field=models.BooleanField(default=False),
        ),
    ]
