# Generated by Django 4.2.2 on 2023-06-19 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_customeraddress_default_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='order',
            new_name='customer',
        ),
    ]
