# Generated by Django 4.2.2 on 2023-06-19 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_customer_address_alter_customeraddress_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
