# Generated by Django 4.2.2 on 2023-06-19 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_productrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrating',
            old_name='review',
            new_name='reviews',
        ),
    ]
